# Generated by Django 4.1.3 on 2022-11-02 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0002_alter_address_district"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="provider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="providers.provider",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="provider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="providers.provider",
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="provider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="providers.provider",
            ),
        ),
        migrations.AlterField(
            model_name="immunisationstatement",
            name="provider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="providers.provider",
            ),
        ),
        migrations.AlterField(
            model_name="nextofkin",
            name="provider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="providers.provider",
            ),
        ),
        migrations.AlterField(
            model_name="otherdetail",
            name="provider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="providers.provider",
            ),
        ),
    ]
