# Generated by Django 4.1.3 on 2022-11-07 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0003_alter_address_provider_alter_contact_provider_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="email",
            new_name="email1",
        ),
    ]
